#!/bin/bash

set -eou pipefail
shopt -s extglob
shopt -s globstar

SANDBOX_REPO="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" &> /dev/null && pwd )"

function die() {
    echo "ERROR: ${1}" >&2
    if [[ ! -z $(which buildkite-agent 2>/dev/null) ]]; then
        buildkite-agent annotate --style=error "${1}"
    fi
    exit 1
}

if [[ -z "$(which julia 2>/dev/null)" ]]; then
    die "Sandbox requires a Julia v1.6+ installation to function"
fi


if [[ ! -v "BUILDKITE_PLUGIN_SANDBOX_ROOTFS_URL" ]]; then
    die "Sandbox requires a rootfs tarball URL"
fi

if [[ ! -v "BUILDKITE_PLUGIN_SANDBOX_ROOTFS_TREEHASH" ]]; then
    die "Sandbox requires a rootfs treehash"
fi
if ! [[ "${BUILDKITE_PLUGIN_SANDBOX_ROOTFS_TREEHASH}"  =~ ^[[:xdigit:]]{40}$ ]]; then
    die "Sandbox rootfs treehash not 40 hexadecimal characters"
fi

# Install `Sandbox` and `Artifacts` globally
echo "--- Instantiating sandbox environment"
julia --project="${SANDBOX_REPO}/lib" -e "using Pkg; Pkg.instantiate()"

# Perform absurd bash overwriting, so that all future commands are sandboxed
echo "--- Installing bash override"
cp -va /bin/bash /bin/truebash
julia --project="${SANDBOX_REPO}/lib" "${SANDBOX_REPO}/lib/generate_sandboxed_bash.jl" "${BUILDKITE_PLUGIN_SANDBOX_SHELL:-/bin/bash}"
